services:
  nextjs-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nextjs-app
    ports:
     - "80:3000" #maps ec2 80 to docker 3000.
    environment:
     - NODE_ENV=production
    volumes:
     - ./data:/app/data
     - ./data/database.sqlite:/app/database.sqlite
    # Run migrations on container start then start the app
    command: ["/bin/sh", "-c", "npx sequelize-cli db:migrate && npm start"]
    restart: unless-stopped